#! /usr/bin/env python

import os
import sys

args = sys.argv

os.system("python ../data/configfiles/make_clean_config.py")
os.system("python ../data/configfiles/extract_config_doc.py")
if "--nosphinx" not in args:
    os.system("make html")
if "--noweb" not in args:
    os.system("scp -r build/html/* mwaskom@ftp.dialup.mit.edu:pyroi")
