#! /usr/bin/env python

import os
import sys

args = sys.argv

if '-h' in args:
    print "build_doc [--nocfg] [--nosphinx] [--noweb]"
    sys.exit(0)

if "--nocfg" not in args:
    os.system("python ../data/configfiles/make_clean_config.py")
    os.system("python ../data/configfiles/extract_config_doc.py")
if "--nosphinx" not in args:
    os.system("make html")
if "--noweb" not in args:
    os.system("scp -r build/html/* mwaskom@ftp.dialup.mit.edu:pyroi")
